name: Android CI

on:
  push:
    branches: [ v0.0.3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: |
        cd android 
        chmod +x gradlew
        ls -la
    - name: Build with Gradle
      run: ./gradlew build
